### ISSUE TITLE
ADASYN

### ISSUE THREAD

**Issue by roushansr** [dcpatton/credit-card-fraud-detection#1]
***********      from imblearn.over_sampling import ADASYN
ada = ADASYN(random_state=seed)
x_train, y_train = ada.fit_sample(x_train, y_train) ***********

Here I am getting an error called "'ADASYN' object has no attribute 'fit_sample'
![Screenshot 2022-07-17 140136](https://user-images.githubusercontent.com/50791263/179397276-37a279da-f583-4979-a021-14f6015d7409.jpg)
"

**Comment by dcpatton** [comment]
Apparently the imblearn library changed. Issue should be fixed now.
